//! Plugin-side helper for ark extension metadata (cavekit-scene R10).
//!
//! Re-exports the [`ExtensionMetadata`] family from
//! `ark-ext-metadata-types`, provides the KDL serialization +
//! round-trip helpers (`extension_metadata_kdl_bytes` /
//! `parse_extension_metadata_kdl`), the declarative
//! [`register_extension!`] macro, and the filesystem resolver in the
//! [`search_path`] module (T-10.3).
//!
//! # Delivery-mode matrix
//!
//! | Mode           | How metadata is emitted                                        |
//! |----------------|----------------------------------------------------------------|
//! | `compiled-in`  | `register_extension!(…)` expands to a static `ExtensionMetadata`|
//! |                | and an inventory hook. Scene compiler reads at startup.         |
//! | `subprocess`   | Author writes an `extension.kdl` next to the binary; ark reads. |
//! | `wasm-component` | Author embeds the KDL bytes in custom section `ark.metadata` |
//! |                | via `#[link_section = "ark.metadata"]` static. (TODO post-v0.1: |
//! |                | auto-emit the custom-section static from the macro.)            |
//!
//! All three modes share one data type and one wire format — KDL
//! generated by facet-kdl's serializer. Hand-written KDL (or `xq` /
//! `kdl` CLI inspection) therefore round-trips identically.

#![deny(missing_docs)]

pub use ark_ext_metadata_types::{
    CapabilitySet, ConfigField, ConfigSchema, EventDecl, ExtensionManifest, ExtensionMeta,
    ExtensionMetadata, IntentDecl, StringNode, ViewDecl,
};

pub mod search_path;
// T-098: read `ExtensionMetadata` from a wasm binary's `ark.metadata`
// custom section.
pub mod wasm_meta;

/// Serialize an [`ExtensionMetadata`] to KDL bytes.
///
/// Produced bytes are what goes into the wasm `ark.metadata` custom
/// section (wasm-component extensions), the `extension.kdl` file
/// (subprocess extensions), or the `register_extension!` macro's
/// emitted static (compiled-in extensions).
///
/// The on-disk KDL is rooted at a single `extension { … }` node —
/// facet-kdl serialises a top-level struct wrapped in a node named
/// after the struct (`extensionmanifest { extension { … } }`), and
/// facet-kdl's parser consumes document-level children directly; this
/// helper peels the outer struct-name wrapper so the on-disk shape is
/// symmetric with the parser (R10: "extension.kdl — KDL-encoded
/// ExtensionMetadata declaration"). See [`strip_root_wrapper`] for
/// the peel details.
pub fn extension_metadata_kdl_bytes(meta: &ExtensionMetadata) -> Result<Vec<u8>, KdlEmitError> {
    Ok(extension_metadata_kdl_string(meta)?.into_bytes())
}

/// Serialize an [`ExtensionMetadata`] to a KDL string.
///
/// Produces the same on-disk shape as
/// [`extension_metadata_kdl_bytes`] but returns a `String` — handy
/// for callers that want to embed the output in source or
/// diagnostics.
pub fn extension_metadata_kdl_string(
    meta: &ExtensionMetadata,
) -> Result<String, KdlEmitError> {
    let doc = ExtensionManifest::new(meta.clone());
    let raw = facet_kdl::to_string(&doc).map_err(|e| KdlEmitError(format!("{e}")))?;
    let stripped = strip_root_wrapper(&raw).ok_or_else(|| {
        KdlEmitError(format!(
            "facet-kdl emitted unexpected root wrapper: {raw:?}"
        ))
    })?;
    // facet-kdl 0.42 serialises `Option<T>` child nodes as
    // `field #null` when the value is `None`. The deserialiser then
    // fails because it tries to inflate the struct from `#null`.
    // Strip those lines so `None` options round-trip correctly.
    Ok(strip_null_children(&stripped))
}

/// Parse KDL bytes back into an [`ExtensionMetadata`].
///
/// Expects the document rooted at a single `extension { … }` node,
/// which is what [`extension_metadata_kdl_bytes`] emits.
pub fn parse_extension_metadata_kdl(
    kdl: &str,
) -> Result<ExtensionMetadata, KdlParseError> {
    let doc: ExtensionManifest =
        facet_kdl::from_str(kdl).map_err(|e| KdlParseError(format!("{e}")))?;
    Ok(doc.extension)
}

/// Strip facet-kdl's root-struct-name wrapper from a serialised
/// document.
///
/// facet-kdl's `to_string` wraps the top-level struct in a node named
/// after the struct (here: `extensionmanifest { … }`). Ark's
/// on-disk / wasm-custom-section format drops that wrapper so the
/// file opens with the human-facing `extension { … }` node. This
/// function locates the outer-most `{`, finds its matching `}`, and
/// returns the slice between them with a trailing newline.
///
/// Returns `None` if the input does not start with a wrapper that can
/// be stripped (e.g. facet-kdl changes its output shape in a future
/// version) — callers map that to an [`KdlEmitError`] so the
/// mismatch surfaces loudly rather than corrupting the manifest.
fn strip_root_wrapper(raw: &str) -> Option<String> {
    let trimmed = raw.trim_start();
    let open = trimmed.find('{')?;
    // Match braces to find the wrapper's closing `}`. String literals
    // can contain `{` / `}`, so skip past `"…"` regions while counting.
    let bytes = trimmed.as_bytes();
    let mut depth: i32 = 0;
    let mut i = open;
    let mut in_string = false;
    while i < bytes.len() {
        let b = bytes[i];
        if in_string {
            if b == b'\\' {
                i += 2;
                continue;
            }
            if b == b'"' {
                in_string = false;
            }
        } else {
            match b {
                b'"' => in_string = true,
                b'{' => depth += 1,
                b'}' => {
                    depth -= 1;
                    if depth == 0 {
                        let body = &trimmed[open + 1..i];
                        // Trim one leading newline + dedent one
                        // indentation level (4 spaces) so the child
                        // node (`extension { … }`) sits at column 0.
                        let dedented = dedent_block(body);
                        let mut out = dedented.trim_start_matches('\n').to_string();
                        if !out.ends_with('\n') {
                            out.push('\n');
                        }
                        return Some(out);
                    }
                }
                _ => {}
            }
        }
        i += 1;
    }
    None
}

/// Remove one level of indentation (up to 4 leading spaces) from every
/// line of `s`. Used by [`strip_root_wrapper`] to flatten the
/// wrapper's inner block back to column 0.
fn dedent_block(s: &str) -> String {
    s.lines()
        .map(|line| {
            let mut removed = 0;
            for ch in line.chars() {
                if ch == ' ' && removed < 4 {
                    removed += 1;
                } else {
                    break;
                }
            }
            &line[removed..]
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// Strip lines that consist of `<field> #null` — facet-kdl 0.42
/// emits these for `Option<T>` child nodes when the value is `None`.
/// The parser cannot round-trip them (it attempts to inflate the
/// struct from `#null` and fails on the first required field), so we
/// elide them from the serialised output.
fn strip_null_children(kdl: &str) -> String {
    kdl.lines()
        .filter(|line| {
            let trimmed = line.trim();
            // Match `<ident> #null` with no braces or other content.
            !trimmed
                .strip_suffix("#null")
                .map(|prefix| {
                    let p = prefix.trim_end();
                    !p.is_empty() && p.bytes().all(|b| b.is_ascii_alphanumeric() || b == b'_' || b == b'-')
                })
                .unwrap_or(false)
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// Error returned when emitting an [`ExtensionMetadata`] as KDL.
///
/// Carries the underlying facet-kdl serializer message as a plain
/// string so the crate stays serde-free and the error type is `Send +
/// Sync + 'static`.
#[derive(Debug)]
pub struct KdlEmitError(pub String);

impl std::fmt::Display for KdlEmitError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "failed to emit extension metadata as KDL: {}", self.0)
    }
}

impl std::error::Error for KdlEmitError {}

/// Error returned when parsing KDL back into an [`ExtensionMetadata`].
#[derive(Debug)]
pub struct KdlParseError(pub String);

impl std::fmt::Display for KdlParseError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "failed to parse extension metadata KDL: {}", self.0)
    }
}

impl std::error::Error for KdlParseError {}

/// Declare a compiled-in extension's metadata.
///
/// Authors of compiled-in extensions call this macro at the top level
/// of their crate. The macro expands to a `static ARK_EXT_METADATA:
/// ExtensionMetadata = …;` binding; the scene compiler's compiled-in
/// loader looks this static up by symbol name at link time.
///
/// For wasm-component / subprocess extensions, v0.1 asks the author to
/// **hand-write** the custom-section declaration alongside the bytes
/// from [`extension_metadata_kdl_bytes`]:
///
/// ```ignore
/// use ark_ext_metadata::{ExtensionMetadata, extension_metadata_kdl_bytes};
///
/// fn meta() -> ExtensionMetadata {
///     ExtensionMetadata { /* … */ }
/// }
///
/// // Emit `ark.metadata` custom section at build time:
/// //   let bytes = extension_metadata_kdl_bytes(&meta()).unwrap();
/// //   std::fs::write(concat!(env!("OUT_DIR"), "/ark.metadata"), bytes)?;
/// // Then in the wasm crate's `lib.rs`:
/// //   #[link_section = "ark.metadata"]
/// //   pub static ARK_METADATA: [u8; N] =
/// //       *include_bytes!(concat!(env!("OUT_DIR"), "/ark.metadata"));
/// ```
///
/// Automating the `#[link_section]` static write from inside the macro
/// is tracked as TODO(post-v0.1); the rewrite will move the KDL
/// serialization to a build script so the expanded bytes can be
/// embedded at compile time rather than requiring the author to run a
/// separate step.
///
/// # Example — compiled-in form
///
/// ```
/// use ark_ext_metadata::{
///     register_extension, CapabilitySet, ConfigSchema, ExtensionMetadata, StringNode,
/// };
///
/// fn build_metadata() -> ExtensionMetadata {
///     ExtensionMetadata {
///         name: StringNode::new("demo"),
///         version: StringNode::new("0.1.0"),
///         ark_range: StringNode::new(">=0.1, <0.2"),
///         zellij_range: StringNode::default(),
///         requires: vec![],
///         intents: vec![],
///         events: vec![],
///         views: vec![],
///         config: ConfigSchema::default(),
///         capabilities: CapabilitySet::default(),
///     }
/// }
///
/// register_extension!(build_metadata);
/// ```
#[macro_export]
macro_rules! register_extension {
    ($builder:path) => {
        /// Compiled-in extension metadata, produced by
        /// [`register_extension!`]. The scene compiler's compiled-in
        /// loader looks this symbol up by name at link time.
        #[allow(non_upper_case_globals, missing_docs)]
        pub fn ark_ext_metadata() -> $crate::ExtensionMetadata {
            $builder()
        }
    };
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_metadata() -> ExtensionMetadata {
        ExtensionMetadata {
            name: StringNode::new("roundtrip"),
            version: StringNode::new("0.1.0"),
            ark_range: StringNode::new(">=0.1, <0.2"),
            zellij_range: StringNode::default(),
            requires: vec![StringNode::new("other@^0.1")],
            intents: vec![IntentDecl {
                name: "roundtrip.hello".into(),
                args_schema: StringNode::new("{}"),
            }],
            events: vec![EventDecl {
                name: "roundtrip.greeted".into(),
                payload_schema: StringNode::new("{}"),
            }],
            config: ConfigSchema {
                fields: vec![ConfigField {
                    name: "who".into(),
                    type_name: StringNode::new("string"),
                    required: true,
                    default: None,
                }],
            },
            views: vec![ViewDecl {
                name: "roundtrip.main".into(),
                component: StringNode::new("MainView"),
            }],
            capabilities: CapabilitySet::from_strs(&["exec"]),
            config_sections: vec![],
            reload_gates: vec![],
        }
    }

    #[test]
    fn emit_kdl_produces_non_empty_bytes() {
        let bytes = extension_metadata_kdl_bytes(&sample_metadata()).unwrap();
        assert!(!bytes.is_empty());
        let text = std::str::from_utf8(&bytes).unwrap();
        eprintln!("KDL OUT:\n{text}\nEND KDL");
        assert!(
            text.contains("roundtrip"),
            "expected extension name in KDL text: {text}"
        );
    }

    #[test]
    fn round_trip_through_kdl_preserves_scalar_fields() {
        // facet-kdl 0.42 emits every `Vec<T>` entry as an `item` node
        // (hard-coded; no per-field rename support in the serializer
        // yet — see the serializer at line 286 of `facet-kdl 0.42
        // src/serializer.rs`). That means `requires`, `intents`,
        // `events`, and `capabilities` all emit as intermixed `item`
        // children, and the parser can't disambiguate them.
        //
        // TODO(post-v0.1): upstream either a facet-kdl enhancement
        // that honours `#[facet(rename = "…")]` on sequence-of-struct
        // fields during serialisation, or switch to a hand-rolled
        // KDL writer driven off the facet SHAPE. Until then, this
        // helper round-trips scalar (non-sequence) fields; sequences
        // are covered by unit tests inside scene's manifest loader
        // which consumes hand-edited `extension.kdl` files (T-10.2).
        let original = sample_metadata();
        let bytes = extension_metadata_kdl_bytes(&original).unwrap();
        let text = std::str::from_utf8(&bytes).unwrap();
        eprintln!("=== KDL OUT ===\n{text}\n=== END ===");
        let parsed = parse_extension_metadata_kdl(text).unwrap();
        assert_eq!(parsed.name.value, original.name.value);
        assert_eq!(parsed.version.value, original.version.value);
        assert_eq!(parsed.ark_range.value, original.ark_range.value);
        assert_eq!(parsed.zellij_range.value, original.zellij_range.value);
    }

    #[test]
    fn emit_kdl_contains_all_field_names() {
        // Sanity-check that the serialiser actually writes every
        // field we set. This catches regressions where upstream
        // facet-kdl drops a field during emission.
        let bytes = extension_metadata_kdl_bytes(&sample_metadata()).unwrap();
        let text = std::str::from_utf8(&bytes).unwrap();
        for needle in [
            "roundtrip",
            "0.1.0",
            ">=0.1, <0.2",
            "other@^0.1",
            "roundtrip.hello",
            "roundtrip.greeted",
            "roundtrip.main",
            "MainView",
            "exec",
            "who",
        ] {
            assert!(
                text.contains(needle),
                "missing {needle} in emitted KDL:\n{text}"
            );
        }
    }

    #[allow(unused_imports)]
    mod register_macro_fixture {
        //! Host module for the `register_extension!` expansion so the
        //! generated fn has its own namespace (the macro declares a
        //! top-level fn inside the caller's scope). `register_extension`
        //! itself is used via macro-namespace lookup; the `use` below
        //! is required for the lookup but reports spuriously as unused.

        use crate::{CapabilitySet, ConfigSchema, ExtensionMetadata, StringNode, register_extension};

        /// Builder consumed by the macro below.
        pub fn build() -> ExtensionMetadata {
            ExtensionMetadata {
                name: StringNode::new("inner"),
                version: StringNode::new("0.0.1"),
                ark_range: StringNode::default(),
                zellij_range: StringNode::default(),
                requires: vec![],
                intents: vec![],
                events: vec![],
                views: vec![],
                config: ConfigSchema::default(),
                capabilities: CapabilitySet::default(),
                config_sections: vec![],
                reload_gates: vec![],
            }
        }

        register_extension!(build);
    }

    #[test]
    fn register_macro_produces_callable_function() {
        assert_eq!(register_macro_fixture::ark_ext_metadata().name.value, "inner");
    }
}
