#!/usr/bin/env bash
# generate-brew-formula.sh — render the Homebrew formula for ark.
#
# Usage:
#   scripts/generate-brew-formula.sh <version> <owner> <sha_arm_darwin> \
#       <sha_x86_darwin> <sha_arm_linux> <sha_x86_linux> > Formula/ark.rb
#
# Inputs:
#   version         — release version without the leading `v`, e.g. `0.3.1`.
#   owner           — GitHub owner/repo segment (e.g. `rlch`) used in the
#                     release URL pattern. `<owner>/ark` is assumed.
#   sha_arm_darwin  — sha256 of `ark-<version>-aarch64-apple-darwin.tar.xz`.
#   sha_x86_darwin  — sha256 of `ark-<version>-x86_64-apple-darwin.tar.xz`.
#   sha_arm_linux   — sha256 of `ark-<version>-aarch64-unknown-linux-gnu.tar.xz`.
#   sha_x86_linux   — sha256 of `ark-<version>-x86_64-unknown-linux-gnu.tar.xz`.
#
# Output:
#   A complete Homebrew formula written to stdout. Redirect into
#   `Formula/ark.rb` in the tap repo. The formula references GitHub release
#   tarballs produced by `.github/workflows/release.yml` (F-707).
#
# Contract with the tap repo (rlch/homebrew-ark):
#   The tap's `Formula/ark.rb` must install both `ark` and `ark-hook` so the
#   ClaudeCode hook pipeline works out-of-the-box after `brew install`. Keep
#   the `def install` block in sync with the tarball layout staged in
#   release.yml (dist/ark-<version>-<target>/{ark,ark-hook}).

set -euo pipefail

if [[ $# -ne 6 ]]; then
  echo "usage: $0 <version> <owner> <sha_arm_darwin> <sha_x86_darwin> <sha_arm_linux> <sha_x86_linux>" >&2
  exit 2
fi

version="$1"
owner="$2"
sha_arm_darwin="$3"
sha_x86_darwin="$4"
sha_arm_linux="$5"
sha_x86_linux="$6"

base_url="https://github.com/${owner}/ark/releases/download/v${version}"

cat <<RUBY
# This file is auto-generated by scripts/generate-brew-formula.sh on each
# release tag via .github/workflows/release.yml. Do not edit by hand —
# changes will be overwritten on the next publish. See F-707.
class Ark < Formula
  desc "Zellij-native agent orchestration — spawn AI agents into live sessions"
  homepage "https://github.com/${owner}/ark"
  version "${version}"
  license "MIT OR Apache-2.0"

  on_macos do
    on_arm do
      url "${base_url}/ark-${version}-aarch64-apple-darwin.tar.xz"
      sha256 "${sha_arm_darwin}"
    end
    on_intel do
      url "${base_url}/ark-${version}-x86_64-apple-darwin.tar.xz"
      sha256 "${sha_x86_darwin}"
    end
  end

  on_linux do
    on_arm do
      url "${base_url}/ark-${version}-aarch64-unknown-linux-gnu.tar.xz"
      sha256 "${sha_arm_linux}"
    end
    on_intel do
      url "${base_url}/ark-${version}-x86_64-unknown-linux-gnu.tar.xz"
      sha256 "${sha_x86_linux}"
    end
  end

  def install
    bin.install "ark"
    bin.install "ark-hook"
  end

  test do
    assert_match "ark", shell_output("#{bin}/ark --version")
    assert_match "ark-hook", shell_output("#{bin}/ark-hook --version")
  end
end
RUBY
